export const GET_USERS_LOGIN = 'GET_USERS_LOGIN'

export const GET_USERS_ROOM = 'GET_USERS_ROOM'
export const INSERT_USERS_ROOM = 'INSERT_USERS_ROOM'
export const UPDATE_USERS_ROOM = 'UPDATE_USERS_ROOM'

export const GET_USERS_CUSTOMER = 'GET_USERS_CUSTOMER'
export const INSERT_USERS_CUSTOMER = 'INSERT_USERS_CUSTOMER'
export const UPDATE_USERS_CUSTOMER = 'UPDATE_USERS_CUSTOMER'

export const GET_ORDER = 'GET_ORDER'
export const INSERT_ORDER = 'INSERT_ORDER'
export const UPDATE_ORDER = 'UPDATE_ORDER'

export const TIMER_ORDER = 'TIMER_ORDER'








